### ISSUE TITLE
Исправить замечания по 1 этапу

### ISSUE THREAD

**Issue by wldmr-key** [sergeyvj/CourseWork2#1]
ТЗ вполне себе неплохо, но
ужасная функция для администратора "Просмотр статистики"!!! Что за статистика? Корелляционный анализ? Регрессии? Или, все-таки, что-нить попонятнее?
Не очень хорошо сформулирована правильные идеи по запуску системы

> 1.	Важно чтобы, информация, поступающая в систему, была пригодна для обработки;
> 2.	Понять, какие нововведения необходимо осуществить в объекте автоматизации

Концептуальная схема очень спорная - нужно обсуждать

**Comment by sergeyvj** [comment]
Исправил
