### ISSUE TITLE
По научно-исследовательской части

### ISSUE THREAD

**Issue by wldmr-key** [sergeyvj/CourseWork2#2]
Мотивация - "большти очереди" для владельца моек - не очень. Если всегда очереди - это отлично - можно расширяться. Как правильно мотивировать?

Анализ аналогов прекрасен. Но желательно артикулироать вывод: я в свое приложение возьму такие-то достоинства и избегну таких-то недостатков.

Описание предметной области у тебя смыкается с описание функций приложения. Так можно делать, хотя заголовку это перестает соответствовать... Тебе лень лишний раздел сделать? ))

Ну и после такого детального описание напрашивается вставка концептуальной схемы - не находишь?

**Comment by sergeyvj** [comment]
Исправил (все функции приложения перенёс в п.2.4)
