### ISSUE TITLE
Конструкторская часть

### ISSUE THREAD

**Issue by wldmr-key** [sergeyvj/CourseWork2#4]
Знаешь ли ты отличия логической модели от физической? Судя по тексту - не очень ))

Описание алгоритма:

> 4)	производится выборка из базы данных согласно параметрам;

это не всегда так у тебя...

не факт что jwt - это конструирование и ,тем более, архитектурная компонента. на мой вкус- это более уместно в технологической части и вполне можно этому посвятить небольщой раздел. Вообще, мне кажется, что когда ты говоришь об архитектуре ты слишком лаконичен (хотя, возможно, ты это компенсируешь в другой курсовой))

Примеры и иллюстрации - отличные

**Comment by sergeyvj** [comment]
Исправил в полной версии РПЗ
